version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: khangphuc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: khangphuc_db
      MYSQL_USER: khangphuc_user
      MYSQL_PASSWORD: khangphuc_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
